# Generated by Django 5.0.6 on 2024-07-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Companydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('year_founded', models.IntegerField(default=0)),
                ('industry', models.CharField(max_length=255)),
                ('locality', models.TextField()),
                ('country', models.CharField(max_length=255)),
                ('linkedin_url', models.CharField(max_length=255)),
                ('current_employee_estimate', models.IntegerField(default=0)),
                ('total_employee_estimate', models.IntegerField(default=0)),
            ],
        ),
    ]
